/** 墨境 v18 素材库：图片/音频/视频批量导入，IndexedDB 持久化。 */
const MaterialLibrary={DB:'mojing_materials_v1',STORE:'materials',_db:null,
 async _open(){if(this._db)return this._db;return new Promise((resolve,reject)=>{const req=indexedDB.open(this.DB,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(this.STORE)){const s=db.createObjectStore(this.STORE,{keyPath:'id'});s.createIndex('type','type');s.createIndex('createdAt','createdAt')}};req.onsuccess=()=>{this._db=req.result;resolve(this._db)};req.onerror=()=>reject(req.error)})},
 async _all(){const db=await this._open();return new Promise((res,rej)=>{const r=db.transaction(this.STORE,'readonly').objectStore(this.STORE).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})},
 async _put(item){const db=await this._open();return new Promise((res,rej)=>{const r=db.transaction(this.STORE,'readwrite').objectStore(this.STORE).put(item);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})},
 async _delete(id){const db=await this._open();return new Promise((res,rej)=>{const r=db.transaction(this.STORE,'readwrite').objectStore(this.STORE).delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})},
 _type(file){if(file.type.startsWith('image/'))return'image';if(file.type.startsWith('audio/'))return'audio';if(file.type.startsWith('video/'))return'video';return'other'},
 async importFiles(files){const arr=Array.from(files||[]);if(!arr.length)return;let ok=0;for(const file of arr){if(file.size>30*1024*1024){if(window.App?.toast)App.toast(file.name+' 超过30MB，已跳过','error');continue}try{const data=await new Promise((r,j)=>{const fr=new FileReader();fr.onload=()=>r(fr.result);fr.onerror=()=>j(fr.error);fr.readAsDataURL(file)});await this._put({id:'mat_'+Date.now()+'_'+Math.random().toString(36).slice(2),name:file.name,type:this._type(file),mime:file.type,data,createdAt:Date.now(),size:file.size});ok++}catch(e){console.warn('[MaterialLibrary]',e)}}if(window.App?.toast)App.toast(`已导入 ${ok}/${arr.length} 个素材`,'success');this.renderPage()},
 async clear(){if(!confirm('确定清空统一素材库？旧背景库/音乐库不会被删除。'))return;const all=await this._all();for(const x of all)await this._delete(x.id);this.renderPage()},
 async renderPage(){const page=document.getElementById('page-material-library');if(!page)return;let items=[];try{items=await this._all()}catch(e){console.warn(e)}items.sort((a,b)=>b.createdAt-a.createdAt);page.innerHTML=`<div class="mo-material-page"><div class="mo-material-head"><div><h1>素材库</h1><p>统一管理立绘、背景、CG、音乐与视频；支持一次从相册多选。</p></div></div><div class="mo-material-actions"><button class="mo-material-btn primary" onclick="MaterialLibrary.pick()">＋ 批量导入素材</button><button class="mo-material-btn" onclick="App.navigate('background')">背景库</button><button class="mo-material-btn" onclick="App.navigate('music')">音乐库</button><button class="mo-material-btn" onclick="App.navigate('cg-gallery')">CG画廊</button><button class="mo-material-btn" onclick="MaterialLibrary.clear()">清空统一库</button><input id="moMaterialInput" type="file" hidden multiple accept="image/*,audio/*,video/*"></div><div class="mo-material-grid">${items.length?items.map(x=>this._card(x)).join(''):'<div class="mo-material-empty">还没有统一素材。点击“批量导入素材”即可从手机相册一次选择多张图片，也可选择音频/视频。</div>'}</div></div>`;const input=document.getElementById('moMaterialInput');if(input)input.onchange=e=>this.importFiles(e.target.files)},
 _esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))},
 _card(x){x=x||{};const name=this._esc(x.name||'未命名素材');let media='';if(x.type==='image')media=`<img loading="lazy" src="${x.data}" alt="">`;else if(x.type==='video')media=`<video src="${x.data}" controls></video>`;else if(x.type==='audio')media=`<div style="padding:12px;width:100%"><div style="font-size:34px">♫</div><audio src="${x.data}" controls style="width:100%"></audio></div>`;else media='<span>文件</span>';return `<article class="mo-material-card"><div class="mo-material-thumb">${media}</div><div class="mo-material-meta"><b title="${name}">${name}</b><small>${x.type||'other'} · ${((x.size||0)/1024/1024).toFixed(1)}MB</small><button class="mo-material-btn" style="margin-top:7px;padding:5px 8px" onclick="MaterialLibrary.remove('${x.id}')">删除</button></div></article>`},
 async remove(id){await this._delete(id);this.renderPage()},pick(){document.getElementById('moMaterialInput')?.click()}
};window.MaterialLibrary=MaterialLibrary;