/* 墨境 NEW UI — independent application shell. Legacy presentation code is not used. */
(function(){
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const routes=['home','works','runtime','map','npc','hero','quest','inventory','relations','chat','save-manager','storyline','storytree','timeline','events','weather','letter','cg-gallery','background','music','worldbook','worldview','memory','presets','prompts','regex','api','assistant','import','backup','settings','settings-hub','beautify','ui-diy','design-suite','custom','custom-creator','button-customizer','chapter-editor','text-novel','world-notes','notes','baike','achievement','badge-wall','alliance','family','political','conspiracy','forum','mail','fun','juncheng','mobile-preview','pwa','plugins','skill-discovery','system-builder','code-patcher','world-selector'];
const labels={home:'首页',works:'作品库',runtime:'进入故事',map:'天下图',npc:'人物志',hero:'主角',quest:'任务',inventory:'行囊',relations:'关系',chat:'私语', 'save-manager':'存档',storyline:'剧情线',storytree:'分支树',timeline:'时间线',events:'事件',weather:'天象',letter:'书信','cg-gallery':'画廊',background:'背景',music:'乐章',worldbook:'世界书',worldview:'世界观',memory:'记忆',presets:'预设',prompts:'提示词',regex:'正则',api:'接口',assistant:'墨灵',import:'导入',backup:'备份',settings:'设置','settings-hub':'系统设置',beautify:'美化','ui-diy':'界面编辑','design-suite':'设计工坊',custom:'自定义','custom-creator':'功能创建','button-customizer':'按钮配置','chapter-editor':'章节编辑','text-novel':'文字小说','world-notes':'世界札记',notes:'笔记',baike:'百科',achievement:'成就','badge-wall':'徽章墙',alliance:'势力',family:'家族',political:'政治',conspiracy:'暗线',forum:'广场',mail:'邮箱',fun:'趣味',juncheng:'政务', 'mobile-preview':'手机预览',pwa:'离线应用',plugins:'插件','skill-discovery':'能力中心','system-builder':'系统搭建','code-patcher':'代码修补','world-selector':'选择世界'};
const data={world:'长安夜雨',chapter:'第三章 · 雨落朱雀门',time:'子时 23:17',weather:'细雨',location:'朱雀门外',hero:'沈昭',affection:61};
const placeholder='data:image/svg+xml;charset=utf-8,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 760"><defs><linearGradient id="a" x2="1" y2="1"><stop stop-color="#e9ded9"/><stop offset=".55" stop-color="#bca7a3"/><stop offset="1" stop-color="#5b4a50"/></linearGradient></defs><rect width="1200" height="760" fill="url(#a)"/><circle cx="930" cy="145" r="105" fill="#fff" opacity=".4"/><path d="M0 560Q220 420 430 540T800 510T1200 450V760H0Z" fill="#554b50" opacity=".55"/><path d="M0 630Q260 520 520 620T1200 550V760H0Z" fill="#29252a" opacity=".42"/></svg>');
const art=()=>window.NovelRuntime?.state?.currentBgUrl||window.NovelRuntime?._state?.currentBgUrl||placeholder;
const char=()=>window.NovelRuntime?.state?.currentNpcImage||window.NovelRuntime?._state?.currentNpcImage||placeholder;
function go(r){location.hash='#/'+(routes.includes(r)?r:'home')}
function current(){let r=(location.hash||'#/home').slice(2).split('?')[0];return routes.includes(r)?r:'home'}
function back(){const h=location.hash;if(h&&h!=='#/home'){go('home')}else window.history.back()}
function img(u,cl=''){return '<img class="'+cl+'" src="'+esc(u||placeholder)+'" alt="">'}
function top(active){return '<header class="nx-top"><button class="nx-logo" data-go="home"><strong>墨境</strong><small>MO JING · INTERACTIVE NOVEL</small></button><nav>'+[['home','首页'],['works','作品'],['runtime','阅读'],['map','地图'],['npc','人物']].map(x=>'<button class="'+(active===x[0]?'on':'')+'" data-go="'+x[0]+'">'+x[1]+'</button>').join('')+'</nav><div class="nx-top-actions"><button data-go="assistant">墨灵</button><button data-go="settings">设置</button></div></header>'}
function bottom(active){return '<footer class="nx-bottom">'+[['home','首页','⌂'],['works','作品','▤'],['runtime','阅读','▶'],['map','地图','⌖'],['npc','人物','♙']].map(x=>'<button class="'+(active===x[0]?'on':'')+'" data-go="'+x[0]+'"><i>'+x[2]+'</i><span>'+x[1]+'</span></button>').join('')+'</footer>'}
function gameRail(){return '<aside class="nx-rail"><button data-go="map"><i>⌖</i><span>地图</span></button><button data-go="npc"><i>♙</i><span>人物</span></button><button data-go="quest"><i>◇</i><span>任务</span></button><button data-go="inventory"><i>□</i><span>行囊</span></button><button data-go="relations"><i>♧</i><span>关系</span></button><button data-go="save-manager"><i>▤</i><span>存档</span></button></aside>'}
function cover(title,sub,meta){return '<article class="nx-cover" data-go="runtime"><div class="nx-cover-art">'+img(art())+'<em>互动小说</em></div><h3>'+esc(title)+'</h3><p>'+esc(sub)+'</p><small>'+esc(meta)+'</small></article>'}
function home(){return '<div class="nx-platform">'+top('home')+'<main class="nx-home"><section class="nx-welcome"><div><span>推荐 · 互动阅读</span><h1>今天，进入一个新的世界。</h1><p>高自由度 AI 群像文游。角色会行动，世界会推进，你的选择会留下痕迹。</p><div><button class="nx-primary" data-go="runtime">继续故事</button><button data-go="works">浏览作品</button></div></div><div class="nx-welcome-art">'+img(art())+'<div><b>长安夜雨</b><span>第三章 · 雨落朱雀门</span></div></div></section><div class="nx-tabs"><b>推荐</b><span>新作</span><span>勤更</span><span>完结</span><span>古风</span><span>现代</span><span>奇幻</span><span>科幻</span></div><section class="nx-section"><header><div><span>EDITOR'S PICK</span><h2>编辑推荐</h2></div><button data-go="works">全部作品 ›</button></header><div class="nx-grid">'+cover('长安夜雨','古风 · 群像 · 权谋','正在阅读')+cover('霓虹第七区','现代 · 悬疑 · 群像','12 名角色在线')+cover('星海边境','科幻 · 冒险 · 多线','世界运行中')+cover('白塔学院','奇幻 · 校园 · 成长','全线开放')+'</div></section></main>'+bottom('home')+'</div>'}
function works(){return '<div class="nx-platform">'+top('works')+'<main class="nx-catalog"><header><div><span>WORKS / LIBRARY</span><h1>作品库</h1><p>像逛互动阅读平台一样选择你的下一段人生。</p></div><button class="nx-primary" data-go="custom-creator">＋ 创建作品</button></header><div class="nx-filters"><b>全部</b><span>古风</span><span>现代</span><span>奇幻</span><span>科幻</span><span>悬疑</span><span>群像</span><span>恋爱</span></div><div class="nx-grid nx-grid-large">'+cover('长安夜雨','古风 · 群像 · 权谋','第 3 章')+cover('霓虹第七区','现代 · 悬疑','第 12 日')+cover('星海边境','科幻 · 冒险','第 8 节')+cover('白塔学院','奇幻 · 校园','序章')+cover('浮光旧梦','现代 · 情感','多结局')+cover('无名档案','悬疑 · 推理','新作')+'</div></main>'+bottom('works')+'</div>'}
function runtime(){return '<div class="nx-game">'+img(art(),'nx-game-bg')+'<div class="nx-game-vignette"></div><header class="nx-game-head"><button data-back>‹ 返回</button><div><strong>'+data.world+'</strong><small>'+data.chapter+'　·　'+data.location+'</small></div><div><span>'+data.time+'</span><button data-go="save-manager">存档</button><button data-go="settings">☰</button></div></header><div class="nx-game-state"><b>'+data.weather+'</b><i></i><span>声望 32</span><i></i><span>银两 128</span></div>'+gameRail()+'<section class="nx-dialog"><header><b>'+data.hero+'</b><span>好感 '+data.affection+'</span></header><p id="nx-dialog-text">雨落得很密。朱雀门的灯火被水汽揉成一片，你看见沈昭停在檐下，没有回头。</p><div class="nx-choices"><button data-say="继续观察">继续观察</button><button data-say="走过去">走过去</button><button data-say="叫住他">叫住他</button></div><div class="nx-compose"><textarea id="nx-input" placeholder="自由输入：你可以说任何话，也可以描述行动……"></textarea><button id="nx-send">发送</button></div></section><button class="nx-game-return" data-back>返回作品</button></div>'}
function map(){return '<div class="nx-map">'+img(art(),'nx-map-bg')+'<div class="nx-map-filter"></div><header class="nx-game-head"><button data-back>‹</button><div><strong>天下图</strong><small>'+data.world+' · 当前区域</small></div><button data-go="settings">☰</button></header><div class="nx-map-name">长安</div><div class="nx-map-lines"></div><button class="nx-place p1" data-go="runtime"><b>皇城</b><small>权力中心</small></button><button class="nx-place p2" data-go="runtime"><b>西市</b><small>商旅云集</small></button><button class="nx-place p3" data-go="runtime"><b>洛水</b><small>雨声很近</small></button><button class="nx-place p4" data-go="runtime"><b>朱雀门</b><small>当前位置</small></button><section class="nx-map-sheet"><span>当前地点 · 朱雀门</span><h2>夜雨中的城门</h2><p>这里连接皇城与坊市。你可以移动、观察、拜访角色或等待世界继续运行。</p><button class="nx-primary" data-go="runtime">进入地点</button></section></div>'}
function npc(){let ns=[['沈昭','摄政王','61','82'],['顾青辞','游侠','17','56'],['林晚','医师','74','74'],['闻人渡','监察使','—','31'],['苏槐','太史令','38','49'],['宁绾','商会主人','52','66']];return '<div class="nx-platform">'+top('npc')+'<main class="nx-people"><header><div><span>CAST / RELATIONS</span><h1>人物志</h1><p>他们拥有自己的日程、关系、目标与记忆。</p></div><button data-go="relations">查看关系图谱 →</button></header><div class="nx-people-grid">'+ns.map(n=>'<article data-go="hero"><div>'+img(char(),'nx-person-art')+'<em>行动中</em></div><section><span>'+n[1]+'</span><h2>'+n[0]+'</h2><div class="nx-meter"><i style="width:'+(n[2]==='—'?20:n[2])+'%"></i></div><small>好感 '+n[2]+'　羁绊 '+n[3]+'</small></section></article>').join('')+'</div></main>'+bottom('npc')+'</div>'}
function hero(){return '<div class="nx-profile"><aside>'+img(char(),'nx-profile-art')+'</aside><main><button data-back>‹ 返回人物志</button><span>CHARACTER PROFILE</span><h1>沈昭</h1><p class="nx-role">摄政王 · 长安权力核心</p><div class="nx-stats"><b>61<small>好感</small></b><b>82<small>羁绊</small></b><b>7<small>共同事件</small></b></div><hr><h3>当前状态</h3><p>正在皇城处理政务。你离开之后，他仍会按照自己的日程行动。</p><div class="nx-actions"><button data-go="chat">与他交谈</button><button data-go="relations">查看关系</button><button data-go="timeline">共同经历</button></div></main></div>'}
function systemPage(r){const title=labels[r]||r;const groups={api:['连接与模型','API 地址、密钥、模型、请求格式、超时与错误诊断'],assistant:['墨灵工作台','分析文件、搜索代码、生成修改方案、预览并在授权后写入'],memory:['长期记忆','混合检索、时间衰减、重要度、固定记忆与手动整理'],worldbook:['世界书','世界规则、地点、势力、人物背景与触发条件'],presets:['预设管理','角色口吻、行为逻辑、边界与场景规则'],prompts:['提示词层级','墨灵助手 → 预设 → 世界书 → 记忆'],regex:['正则规则','文本清洗、结构化输出与安全过滤'],settings:['阅读设置','界面、字体、动画、声音、输入方式与隐私'],quest:['任务委托','主线、支线、隐藏任务与奖励'],inventory:['行囊','道具、装备、材料与使用记录'],relations:['关系图谱','角色之间的好感、羁绊、敌对与势力关系'],storyline:['剧情线','章节、事件节点、分歧与结局'],storytree:['剧情分支树','可视化查看故事分支与当前路径'],timeline:['世界时间线','已经发生、正在发生、即将发生的事件'],events:['世界事件','随机事件、角色事件与环境事件'],weather:['天象时辰','日期、时间、天气、季节与世界时钟'],letter:['飞鸽传书','角色来信、系统信件与待处理消息'],background:['背景库','场景图、立绘背景与动态背景'],music:['音乐库','BGM、环境音、MP3 与播放队列'], 'cg-gallery':['CG 鉴赏','剧情 CG、插画与收藏'],import:['素材导入','图片、音频、视频、世界书、角色资料批量导入'],backup:['备份恢复','导出、导入、版本快照与恢复'],beautify:['主题美化','作品主题、阅读皮肤与界面密度'], 'ui-diy':['界面编辑','按钮、布局、字体、颜色与阅读组件'], 'design-suite':['设计工坊','页面原型、组件与视觉系统'],custom:['自定义应用','创建自己的功能入口与工作台'], 'custom-creator':['功能创建','通过配置创建新的世界功能'], 'button-customizer':['按钮配置','管理游戏内操作按钮与位置'], 'chapter-editor':['章节编辑','章节文本、事件、选择与条件'], 'text-novel':['文字小说','Markdown / 纯文字阅读模式'], 'world-notes':['世界札记','世界资料、灵感与编辑笔记'],notes:['记事册','私人笔记与剧情草稿'],baike:['百科','世界知识与角色资料查询'],achievement:['成就','故事成就与收藏'], 'badge-wall':['徽章墙','特殊称号与纪念徽章'],alliance:['势力','组织、家族、联盟与资源'],family:['家族','家谱、成员、继承与关系'],political:['政治','势力态势、政策与权力'],conspiracy:['暗线','秘密、阴谋与隐藏条件'],forum:['交流广场','作品交流、世界讨论与创作者动态'],mail:['邮箱','系统通知与作品消息'],fun:['趣味玩法','小游戏、彩蛋与随机玩法'],juncheng:['政务','君成录式政务、内政、资源与事件'], 'mobile-preview':['手机预览','模拟手机端阅读与操作布局'],pwa:['离线应用','安装、缓存与离线运行'],plugins:['插件','可授权扩展能力'], 'skill-discovery':['能力中心','AI、媒体、世界模拟与创作能力'], 'system-builder':['系统搭建','创建世界规则、数值系统与事件系统'], 'code-patcher':['代码修补','搜索源码、生成补丁、预览后授权写入'], 'world-selector':['世界选择','选择作品、创建世界或继续最近旅程'],presets:['预设管理','角色预设与世界预设']};let g=groups[r]||[title,'墨境功能模块'];return '<div class="nx-admin"><header class="nx-admin-head"><button data-back>‹ 返回</button><div><span>MO JING / SYSTEM</span><h1>'+esc(g[0])+'</h1><p>'+esc(g[1])+'</p></div><button data-go="home">首页</button></header><main class="nx-admin-main"><section class="nx-paper"><div class="nx-paper-head"><span>当前模块</span><strong>'+esc(title)+'</strong></div><div class="nx-form"><label>状态 <b>已就绪</b></label><label>运行模式 <b>沉浸式</b></label><label>数据来源 <b>本地世界数据</b></label><label>说明 <b>此面板使用统一的新 UI，旧版页面不再作为视觉入口。</b></label></div><div class="nx-admin-actions"><button class="nx-primary" data-action="demo">打开模块</button><button data-back>取消 / 返回</button></div></section><aside class="nx-side-note"><span>墨境提示</span><h3>每一次修改都应当可撤销。</h3><p>导入、生成、代码修改等高风险操作先预览，再由你确认写入。</p></aside></main></div>'}
function render(){const r=current();let html=r==='home'?home():r==='works'?works():r==='runtime'?runtime():r==='map'?map():r==='npc'?npc():r==='hero'?hero():systemPage(r);document.body.innerHTML=html;bind()}
async function send(text){const box=$('#nx-dialog-text');if(!box)return;box.textContent='正在联系 AI……';try{let out='';if(window.VNEngine?.send)out=await window.VNEngine.send(text);else if(window.NovelRuntime?.genAIReply)out=await window.NovelRuntime.genAIReply(text);else out='当前尚未连接 AI 服务。请进入「接口」检查 API 地址、Key、CORS、模型名称与额度。';box.textContent=out||'AI 没有返回内容。请检查接口返回是否为有效 JSON。'}catch(e){box.textContent='连接失败：'+(e?.message||'未知错误')+'。请检查网络、API 地址、Key/权限、CORS、模型额度以及返回格式。'}}
function bind(){ $$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$$('[data-back]').forEach(b=>b.onclick=back);$$('[data-say]').forEach(b=>b.onclick=()=>send(b.dataset.say));const s=$('#nx-send'),i=$('#nx-input');if(s)s.onclick=()=>{const t=i?.value.trim();if(t){i.value='';send(t)}};if(i)i.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')s?.click()});$$('[data-action="demo"]').forEach(b=>b.onclick=()=>alert('模块已打开。真实数据功能将沿用原有引擎，视觉与导航由新版统一接管。'))}
window.addEventListener('hashchange',render);window.addEventListener('keydown',e=>{if(e.key==='Escape'&&current()!=='home')back()});if(!location.hash)location.hash='#/home';else render();
})();
