/* 墨境 v8 页面编排层：高级互动文游页面 + 安全导航。 */
(function(){'use strict';
const names={home:'墨境',runtime:'沉浸式剧情',api:'连接中心',npc:'人物志',background:'背景库',music:'音乐库',map:'天下图',status:'状态',prompts:'提示词',memory:'长记忆',presets:'预设',regex:'正则引擎',worldbook:'世界书','world-selector':'世界选择',hero:'我的角色',assistant:'墨境助手',relations:'关系网',storyline:'故事线',chat:'群像聊天',settings:'系统设置',inventory:'背包',quest:'任务委托',timeline:'时间线',events:'世界事件','cg-gallery':'CG画廊'};
const nav=[['home','首页'],['world-selector','世界'],['runtime','剧情'],['map','地图'],['npc','人物'],['assistant','助手'],['settings','设置']];
const routeStack=[];let last='';
function route(){return(location.hash||'#home').replace(/^#/,'')||'home'}
function go(p){if(!p)return;if(route()!==p)routeStack.push(route());try{if(window.App&&typeof App.navigate==='function'){App.navigate(p);return true}if(window.App&&typeof App.go==='function'){App.go(p);return true}}catch(e){toast('跳转失败：'+(e.message||e));return false}location.hash='#'+p;return true}
function back(){const p=routeStack.pop();if(p){goWithoutStack(p);return}try{if(window.App&&typeof App.back==='function'){App.back();return}}catch(e){}history.back()}
function goWithoutStack(p){const x=routeStack.length;try{if(window.App&&typeof App.navigate==='function'){App.navigate(p);return}if(window.App&&typeof App.go==='function'){App.go(p);return}}catch(e){}location.hash='#'+p;while(routeStack.length>x)routeStack.pop()}
function toast(m){try{window.App?.toast?.(m,'error',3500);return}catch(e){}console.warn('[墨境]',m)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function data(){let cast=[];try{cast=window.MOWorldV2?.getGroupCast?.(6)||window.MOWorldV2?.getProfiles?.()?.slice(0,6)||[]}catch(e){}let mem=0;try{mem=window.LongMemory?.search?.('',10000)?.length||0}catch(e){}return{cast,mem}}
function pageContent(p){const d=data();if(p==='home')return `<div class="v8-hero"><span class="v8-eyebrow">INTERACTIVE STORY PLATFORM</span><h1>墨境</h1><p>让世界自己运转，让你的选择成为剧情。</p><div class="v8-actions-grid"><button data-route="runtime"><b>开始冒险</b><small>进入沉浸式视觉小说</small></button><button data-route="world-selector"><b>选择世界</b><small>现代 · 古风 · 西幻 · 科幻</small></button><button data-route="hero"><b>我的角色</b><small>创建并管理玩家身份</small></button><button data-route="settings"><b>系统设置</b><small>API、声音、画面与玩法</small></button></div></div>`;
if(p==='world-selector')return `<div class="v8-page"><span class="v8-eyebrow">WORLDS</span><h2>选择你的世界</h2><p>世界类型不设限。进入后可继续编辑世界书、人物与规则。</p><div class="v8-card-grid"><button data-route="runtime"><strong>当前世界</strong><small>继续上次故事</small></button><button data-route="map"><strong>天下图</strong><small>从地图开始探索</small></button><button data-route="npc"><strong>人物志</strong><small>查看世界中的角色</small></button><button data-route="worldbook"><strong>世界书</strong><small>设定历史、势力与规则</small></button></div></div>`;
if(p==='map')return `<div class="v8-page v8-map-page"><span class="v8-eyebrow">WORLD MAP</span><h2>天下图</h2><p>地点、势力与探索入口集中于此。</p><div class="v8-map-canvas"><div class="v8-map-marker m1">主城</div><div class="v8-map-marker m2">旧城区</div><div class="v8-map-marker m3">远方</div><div class="v8-map-hint">选择地点后进入场景</div></div><div class="v8-inline-actions"><button data-route="runtime">进入剧情</button><button data-route="worldbook">编辑世界</button></div></div>`;
if(p==='npc')return `<div class="v8-page"><span class="v8-eyebrow">CAST</span><h2>人物志</h2><p>每个人都有自己的生活、目标、情绪与关系，不是等待玩家点击的按钮。</p><div class="v8-character-grid">${(d.cast.length?d.cast:[{name:'世界角色',mood:'待探索',activity:'等待世界事件'}]).map((x,i)=>`<article><div class="v8-avatar">${esc((x.name||'角').slice(0,1))}</div><div><strong>${esc(x.name||'未命名角色')}</strong><small>${esc(x.activity||'独立生活')} · ${esc(x.mood||'平静')}</small></div><button data-route="runtime">进入</button></article>`).join('')}</div></div>`;
return `<div class="v8-page"><span class="v8-eyebrow">${esc((names[p]||'墨境').toUpperCase())}</span><h2>${esc(names[p]||'墨境世界')}</h2><p>这一模块保留原有业务能力，并使用统一高级文游导航。</p><div class="v8-card-grid"><button data-route="home"><strong>返回首页</strong><small>不丢失当前进度</small></button><button data-route="runtime"><strong>继续剧情</strong><small>回到沉浸式舞台</small></button><button data-route="assistant"><strong>墨境助手</strong><small>让助手协助编辑与创作</small></button><button data-route="settings"><strong>设置</strong><small>连接与系统配置</small></button></div>${p==='memory'?`<div class="v8-stat">长期记忆条目：<b>${d.mem}</b></div>`:''}</div>`}
function mount(){if(document.getElementById('moV8Stage'))return;const el=document.createElement('div');el.id='moV8Stage';el.innerHTML='<div class="v8-head"><div><span class="v8-title">墨境</span><span class="v8-sub" id="moV8Sub"></span></div><div class="v8-actions"><button class="v8-btn" data-v8="back">返回</button><button class="v8-btn" data-v8="home">首页</button><button class="v8-btn" data-v8="more">更多</button></div></div><div class="v8-body" id="moV8Body"></div><div class="v8-foot" id="moV8Foot"></div>';document.body.appendChild(el);el.addEventListener('click',e=>{const r=e.target.closest('[data-route]');if(r){go(r.dataset.route);return}const b=e.target.closest('[data-v8]');if(!b)return;const a=b.dataset.v8;if(a==='back')back();if(a==='home')go('home');if(a==='more')go('settings')})}
function refresh(){mount();const p=route(),page=document.getElementById('page-'+p),shell=document.getElementById('moV8Stage');document.body.classList.add('mo-v8-app');document.querySelectorAll('.page-view').forEach(x=>x.classList.toggle('v8-immersive',x===page));const sub=document.getElementById('moV8Sub');if(sub)sub.textContent=names[p]||'墨境世界';const body=document.getElementById('moV8Body');if(body&&p!=='runtime')body.innerHTML=pageContent(p);shell.classList.toggle('v8-runtime-hidden',p==='runtime');const foot=document.getElementById('moV8Foot');if(foot)foot.innerHTML=nav.map(([id,label])=>'<button class="v8-nav '+(id===p?'active':'')+'" data-v8-route="'+id+'">'+esc(label)+'</button>').join('');foot?.querySelectorAll('[data-v8-route]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.v8Route)))}
function boot(){refresh();window.addEventListener('hashchange',()=>setTimeout(refresh,0));new MutationObserver(()=>{if(!document.getElementById('moV8Stage'))mount()}).observe(document.body,{childList:true});window.MOPlatformV8={go,back,refresh}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();