/* 墨境平台能力层 v2：长记忆、媒体工坊、万能助手工作区、主题系统、可解释错误。 */
(function(){'use strict';
const LS={memory:'mo_long_memory_v2',theme:'mo_theme_v2',workspace:'mo_assistant_workspace_v2'};
const read=(k,d)=>{try{const x=localStorage.getItem(k);return x==null?d:JSON.parse(x)}catch(_){return d}};
const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch(_){return false}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tokenize=s=>(String(s||'').toLowerCase().match(/[\u4e00-\u9fff]|[a-z0-9_]+/g)||[]).slice(0,1800);
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function vector(s,n=256){const v=new Float32Array(n);for(const t of tokenize(s)){v[hash(t)%n]+=1;v[hash(':'+t)%n]+=.5;v[hash(t+':semantic')%n]+=.25}let z=0;for(const x of v)z+=x*x;z=Math.sqrt(z)||1;return Array.from(v,x=>x/z)}
function sim(a,b){let x=0;for(let i=0;i<Math.min(a.length,b.length);i++)x+=a[i]*b[i];return x}
function memories(){return read(LS.memory,[]).filter(x=>x&&x.text)}
function addMemory(text,meta={}){const chunks=[];const s=String(text||'').trim();for(let i=0;i<s.length;i+=900){const t=s.slice(i,i+1100).trim();if(t)chunks.push(t)}const list=memories();const now=Date.now();chunks.forEach((t,i)=>{const dup=list.find(x=>x.text===t);if(dup){dup.updatedAt=now;dup.importance=Math.max(dup.importance||.5,meta.importance||.5);return}list.unshift({id:'lm2_'+now.toString(36)+'_'+i, text:t, vector:vector(t), createdAt:now, updatedAt:now, importance:Math.max(0,Math.min(1,Number(meta.importance??.55))),source:meta.source||'manual',tags:meta.tags||[]})});write(LS.memory,list.slice(0,10000));return chunks.length}
function searchMemory(q,k=12){const qt=tokenize(q);const v=vector(q),now=Date.now();return memories().map(m=>{const age=Math.max(0,(now-(m.updatedAt||m.createdAt||now))/86400000);const rec=Math.exp(-age/45);const lex=qt.reduce((n,t)=>n+(String(m.text).toLowerCase().includes(t)?1:0),0);return {...m,score:sim(v,m.vector||vector(m.text))*.68+rec*.12+(m.importance||.5)*.12+Math.min(lex,8)*.01}}).sort((a,b)=>b.score-a.score).slice(0,k)}
window.LongMemoryV2={get:memories,add:addMemory,search:searchMemory,stats:()=>({count:memories().length,chars:memories().reduce((n,x)=>n+x.text.length,0),dimensions:256}),clear:()=>write(LS.memory,[]),export:()=>JSON.stringify(memories(),null,2),import:s=>{const a=JSON.parse(s);if(!Array.isArray(a))throw Error('记忆文件必须是数组');a.forEach(x=>x?.text&&addMemory(x.text,x))}};
/* 与旧 LongMemory 兼容：新引擎优先 v2，旧模块仍可使用。 */
const old=window.LongMemory;window.LongMemory=window.LongMemoryV2;
window.LongMemory.legacy=old||null;
function toast(msg,type='info'){try{window.App?.toast?.(msg,type);return}catch(_){}let x=document.querySelector('.mo6-toast');if(!x){x=document.createElement('div');x.className='mo6-toast';document.body.appendChild(x)}x.textContent=msg;clearTimeout(x._t);x._t=setTimeout(()=>x.remove(),2800)}
function modal(title,html){document.querySelector('.mo6-modal')?.remove();const m=document.createElement('div');m.className='mo6-modal';m.innerHTML=`<section class="mo6-dialog"><header><strong>${esc(title)}</strong><button data-close aria-label="关闭">×</button></header><div class="mo6-body">${html}</div><footer><button data-close>取消</button></footer></section>`;m.addEventListener('click',e=>{if(e.target===m||e.target.closest('[data-close]'))m.remove()});document.body.appendChild(m);return m}
function memoryUI(){const m=modal('长记忆 · 混合检索工作台',`<p class="mo6-muted">256维本地语义向量 + 词法匹配 + 重要度 + 时间衰减。默认保存 10,000 个片段。</p><textarea id="mo6Mem" placeholder="粘贴章节、对话、人物关系、世界事件……"></textarea><div class="mo6-actions"><button id="mo6Add">写入记忆</button><button id="mo6Export">导出</button><button id="mo6Import">导入</button></div><input id="mo6Query" placeholder="检索：例如‘她第一次知道秘密是在什么时候？'"><div id="mo6Results" class="mo6-list"></div>`);const q=id=>m.querySelector('#'+id);q('mo6Add').onclick=()=>{const n=addMemory(q('mo6Mem').value,{source:'memory-workbench'});toast(`已建立 ${n} 个记忆片段`);q('mo6Mem').value=''};q('mo6Query').oninput=()=>{const r=searchMemory(q('mo6Query').value);q('mo6Results').innerHTML=r.map(x=>`<article><b>${esc(x.text.slice(0,260))}</b><small>相关度 ${(x.score*100).toFixed(1)}% · ${esc(x.source||'')}</small></article>`).join('')};q('mo6Export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([LongMemoryV2.export()],{type:'application/json'}));a.download='mojing-long-memory-v2.json';a.click()};q('mo6Import').onclick=()=>{const i=document.createElement('input');i.type='file';i.accept='.json';i.onchange=async()=>{try{LongMemoryV2.import(await i.files[0].text());toast('长记忆导入完成')}catch(e){toast('导入失败：'+e.message,'error')}};i.click()}};
async function image(){const cfg=window.MOAssistant?.config?.()||{};const m=modal('生图工坊',`<p class="mo6-muted">通用世界观：现代、古代、西幻、科幻、末世等均可。需要在“小助手 API”中配置图像端点。</p><textarea id="mo6Prompt" placeholder="例如：雨夜霓虹都市，电影级场景，角色立绘，透明背景……"></textarea><input id="mo6Size" value="1024x1024" placeholder="尺寸"><div class="mo6-actions"><button id="mo6Gen">生成预览</button></div><div id="mo6Image"></div>`);m.querySelector('#mo6Gen').onclick=async()=>{try{const u=await window.MOAssistant.generateImage(m.querySelector('#mo6Prompt').value,m.querySelector('#mo6Size').value);if(!u)throw Error('接口返回中没有图片 URL 或 base64 数据');m.querySelector('#mo6Image').innerHTML=`<img src="${esc(u)}" alt="生成结果" class="mo6-generated">`;toast('图片生成完成')}catch(e){toast('生图失败：'+diagnose(e),'error')}}}
function audio(){const m=modal('声音与 MP3 工坊',`<p class="mo6-muted">音频只保存在当前浏览器 IndexedDB / 对应素材库流程中；可上传 MP3、WAV、OGG 等。</p><input id="mo6Audio" type="file" accept="audio/*" multiple><div id="mo6AudioList" class="mo6-list"></div>`);m.querySelector('#mo6Audio').onchange=e=>{const files=[...e.target.files];m.querySelector('#mo6AudioList').innerHTML=files.map(f=>`<article><b>${esc(f.name)}</b><small>${(f.size/1024/1024).toFixed(2)} MB · ${esc(f.type||'audio')}</small></article>`).join('');try{files.forEach(f=>window.MaterialLibrary?.addFile?.(f))}catch(err){toast('素材库未接收文件：'+diagnose(err),'error')}}}
function assistant(){const w=read(LS.workspace,{files:[],selected:null,plan:'',pending:null});const m=modal('万能小助手 · 工作区',`<div class="mo6-assistant-grid"><aside><b>权限</b><label><input type="checkbox" checked id="mo6Read">读取源文件</label><label><input type="checkbox" id="mo6Write">修改/生成文件（需确认）</label><label><input type="checkbox" checked id="mo6Preview">渲染预览</label><label><input type="checkbox" id="mo6External">访问用户提供的链接</label><input id="mo6Files" type="file" multiple><div id="mo6FileList"></div></aside><main><textarea id="mo6Task" placeholder="告诉小助手：添加什么功能、修改什么 UI、解决什么问题……"></textarea><div class="mo6-actions"><button id="mo6Analyze">分析需求</button><button id="mo6PreviewBtn">预览方案</button><button id="mo6ExportPatch">生成文件</button></div><pre id="mo6Plan"></pre><div class="mo6-muted">执行原则：读取 → 分析 → 生成修改方案 → 预览 → 用户确认 → 写入/导出。不会宣称零错误，也不会绕过浏览器或 GitHub 权限。</div></main></div>`,'wide');const files=m.querySelector('#mo6Files'),list=m.querySelector('#mo6FileList'),task=m.querySelector('#mo6Task'),plan=m.querySelector('#mo6Plan');files.onchange=async()=>{w.files=[];for(const f of files.files){w.files.push({name:f.name,size:f.size,type:f.type,content:(await f.text()).slice(0,200000)})}write(LS.workspace,w);list.innerHTML=w.files.map(f=>`<div>${esc(f.name)} <small>${f.size}B</small></div>`).join('')};m.querySelector('#mo6Analyze').onclick=()=>{const t=task.value.trim();if(!t){toast('请先描述需求','error');return}const names=w.files.map(f=>f.name).join(', ');w.plan={request:t,files:names,createdAt:Date.now(),steps:['检查相关源文件与依赖','定位受影响模块与样式','生成兼容修改方案','生成可预览补丁','等待用户确认后写入']};write(LS.workspace,w);plan.textContent=JSON.stringify(w.plan,null,2);toast('分析方案已生成')};m.querySelector('#mo6PreviewBtn').onclick=()=>{if(!w.plan){toast('请先分析需求','error');return}plan.textContent=JSON.stringify({...w.plan,preview:'此处接入渲染器/沙盒后展示实际页面预览'},null,2);toast('预览阶段已准备')};m.querySelector('#mo6ExportPatch').onclick=()=>{if(!w.plan){toast('请先分析需求','error');return}const out={request:w.plan.request,files:w.files.map(f=>({name:f.name,content:f.content})),note:'这是待确认工作区导出，不会自动覆盖源文件。'};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{type:'application/json'}));a.download='mojing-assistant-workspace.json';a.click();toast('已生成待确认工作区文件')}}
function diagnose(e){const s=String(e?.message||e||'未知错误');if(/401/.test(s))return '401：API 密钥无效或未授权';if(/403/.test(s))return '403：权限不足/CORS/来源限制';if(/404/.test(s))return '404：接口地址不存在';if(/429/.test(s))return '429：请求过于频繁或额度不足';if(/5\d\d/.test(s))return '5xx：服务端异常';if(/Failed to fetch|NetworkError/i.test(s))return '网络/CORS/服务未启动，请检查 endpoint、HTTPS 与浏览器跨域策略';return s}
function theme(){const cur=read(LS.theme,{preset:'cinematic',density:'comfortable'});const m=modal('世界主题系统',`<p class="mo6-muted">平台骨架统一，世界主题可自由切换。</p><select id="mo6Theme"><option value="cinematic">电影叙事</option><option value="ink">墨色东方</option><option value="fantasy">西幻史诗</option><option value="scifi">未来科幻</option><option value="modern">现代都市</option><option value="custom">自定义</option></select><input id="mo6Accent" placeholder="自定义主题色，如 #C9A227"><button id="mo6Save">应用主题</button>`);m.querySelector('#mo6Theme').value=cur.preset;m.querySelector('#mo6Save').onclick=()=>{const x={preset:m.querySelector('#mo6Theme').value,accent:m.querySelector('#mo6Accent').value};write(LS.theme,x);document.documentElement.dataset.moTheme=x.preset;if(x.accent)document.documentElement.style.setProperty('--mo-accent',x.accent);toast('主题已应用');m.remove()}}
function hub(){const items=[['长记忆','memory'],['万能小助手','assistant'],['生图工坊','image'],['MP3 / 声音','audio'],['世界主题','theme'],['群像编排','group']];const m=modal('墨境 · 创作中枢',`<div class="mo6-hub">${items.map(x=>`<button data-go="${x[1]}"><b>${x[0]}</b><small>打开工作台</small></button>`).join('')}</div>`);m.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{m.remove();const a={memory:memoryUI,assistant,image,audio,theme,group:()=>{try{window.WorldSimulation?.openGroup?.()}catch(_){toast('群像模块暂不可用','error')}}};a[b.dataset.go]?.()})}
function bind(){window.MOPlatformV2={memoryUI,assistant,image,audio,theme,hub,diagnose};window.addEventListener('error',e=>{if(e.error)console.warn('[墨境]',diagnose(e.error))});document.addEventListener('click',e=>{const b=e.target.closest('[data-mo-action]');if(!b)return;const a=b.dataset.moAction;({memory:memoryUI,assistant,image,audio,theme,hub}[a]||(()=>{}))()});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();