/* 墨境 v8 页面编排层：高级互动文游页面 + 安全导航 + 功能页重写。 */
(function(){'use strict';
const names={home:'墨境',runtime:'沉浸式剧情',api:'连接中心',npc:'人物志',background:'背景库',music:'音乐库',map:'天下图',status:'状态',prompts:'提示词',memory:'长记忆',presets:'预设',regex:'正则引擎',worldbook:'世界书','world-selector':'世界选择',hero:'我的角色',assistant:'墨境助手',relations:'关系网',storyline:'故事线',chat:'群像聊天',settings:'系统设置',inventory:'背包',quest:'任务委托',timeline:'时间线',events:'世界事件','cg-gallery':'CG画廊'};
const nav=[['home','首页'],['world-selector','世界'],['runtime','剧情'],['map','地图'],['npc','人物'],['assistant','助手'],['settings','设置']];
const routeStack=[];
function route(){return(location.hash||'#home').replace(/^#/,'').split('?')[0]||'home'}
function query(){const q=(location.hash||'').split('?')[1]||'';return new URLSearchParams(q)}
function go(p,params){if(!p)return;if(route()!==p)routeStack.push(route());const target='#'+p+(params?'?'+new URLSearchParams(params).toString():'');try{if(window.App&&typeof App.navigate==='function'){App.navigate(p);if(location.hash!==target)location.hash=target;return true}if(window.App&&typeof App.go==='function'){App.go(p);if(location.hash!==target)location.hash=target;return true}}catch(e){toast('跳转失败：'+reason(e));return false}location.hash=target;return true}
function back(){const p=routeStack.pop();if(p){goWithoutStack(p);return}try{if(window.App&&typeof App.back==='function'){App.back();return}}catch(e){toast('返回失败：'+reason(e))}history.back()}
function goWithoutStack(p){try{if(window.App&&typeof App.navigate==='function'){App.navigate(p);return}if(window.App&&typeof App.go==='function'){App.go(p);return}}catch(e){}location.hash='#'+p}
function reason(e){return e?.message||String(e||'未知错误')}
function toast(m){try{window.App?.toast?.(m,'error',4200);return}catch(e){}console.warn('[墨境]',m)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function data(){let cast=[];try{cast=window.MOWorldV2?.getGroupCast?.(12)||window.MOWorldV2?.getProfiles?.()?.slice(0,12)||[]}catch(e){}let mem=0;try{mem=window.LongMemory?.search?.('',10000)?.length||0}catch(e){}return{cast,mem}}
function profile(id){const d=data();return d.cast.find((x,i)=>String(x.id||x.npcId||i)===String(id))||d.cast[0]||{name:'未命名角色',mood:'平静',activity:'等待世界事件',energy:100}}
function statCard(label,value){return `<div class="v8-stat-card"><small>${esc(label)}</small><b>${esc(value)}</b></div>`}
function formPage(title,eyebrow,desc,body){return `<div class="v8-page"><div class="v8-page-top"><div><span class="v8-eyebrow">${esc(eyebrow)}</span><h2>${esc(title)}</h2><p>${esc(desc)}</p></div><button class="v8-cancel" data-v8="back">取消 / 返回</button></div>${body}</div>`}
function editor(title,key,placeholder){let value='';try{value=localStorage.getItem(key)||''}catch(e){}return formPage(title,'EDITOR','在这里编辑并保存本模块内容；保存失败会明确提示原因。',`<div class="v8-editor"><textarea id="v8Editor" placeholder="${esc(placeholder)}">${esc(value)}</textarea><div class="v8-editor-actions"><button data-save-key="${esc(key)}">保存</button><button data-v8="back">取消</button></div></div>`)}
function pageContent(p){const d=data();
if(p==='home')return `<div class="v8-hero"><span class="v8-eyebrow">INTERACTIVE STORY PLATFORM</span><h1>墨境</h1><p>让世界自己运转，让你的选择成为剧情。</p><div class="v8-actions-grid"><button data-route="runtime"><b>开始冒险</b><small>进入沉浸式视觉小说</small></button><button data-route="world-selector"><b>选择世界</b><small>现代 · 古风 · 西幻 · 科幻</small></button><button data-route="hero"><b>我的角色</b><small>创建并管理玩家身份</small></button><button data-route="settings"><b>系统设置</b><small>API、声音、画面与玩法</small></button></div><div class="v8-quick-row"><button data-route="map">天下图</button><button data-route="npc">人物志</button><button data-route="quest">任务委托</button><button data-route="inventory">背包</button></div></div>`;
if(p==='world-selector')return formPage('选择你的世界','WORLDS','世界类型不设限。选择后继续编辑世界书、人物与规则。',`<div class="v8-world-grid"><article class="v8-world-card active"><span>当前世界</span><h3>墨境世界</h3><p>继续上次故事与世界状态。</p><button data-route="runtime">进入</button></article><article class="v8-world-card"><span>现代</span><h3>都市群像</h3><p>关系、职场、校园与城市事件。</p><button data-route="runtime">载入</button></article><article class="v8-world-card"><span>古风</span><h3>东方长卷</h3><p>江湖、朝堂、家国与群像。</p><button data-route="runtime">载入</button></article><article class="v8-world-card"><span>幻想</span><h3>西幻远境</h3><p>魔法、冒险、公会与种族。</p><button data-route="runtime">载入</button></article><article class="v8-world-card"><span>科幻</span><h3>星海纪元</h3><p>舰队、AI、殖民地与未来政治。</p><button data-route="runtime">载入</button></article></div><div class="v8-inline-actions"><button data-route="worldbook">编辑世界书</button><button data-route="map">查看天下图</button></div>`);
if(p==='npc'){const id=query().get('npc');if(id){const x=profile(id);return formPage(x.name||'角色档案','CHARACTER PROFILE','角色状态、行为倾向与关系入口。',`<div class="v8-profile"><div class="v8-profile-art"><div class="v8-avatar xl">${esc((x.name||'角').slice(0,1))}</div><span>${esc(x.activity||'独立生活')}</span></div><div class="v8-profile-main"><h3>${esc(x.name||'未命名角色')}</h3><p>${esc(x.mood||'平静')} · 精力 ${esc(x.energy??100)}</p><div class="v8-stat-grid">${statCard('当前活动',x.activity||'独立生活')}${statCard('心情',x.mood||'平静')}${statCard('精力',x.energy??100)}</div><div class="v8-profile-actions"><button data-route="runtime">进入剧情</button><button data-route="relations">查看关系</button><button data-route="worldbook">行为设定</button><button data-v8="back">返回人物志</button></div></div></div>`)}return formPage('人物志','CAST','群像角色拥有独立活动、心情、精力与关系。点击角色进入角色档案。',`<div class="v8-character-grid">${(d.cast.length?d.cast:[{name:'世界角色',mood:'待探索',activity:'等待世界事件',energy:100}]).map((x,i)=>{const id=encodeURIComponent(x.id||x.npcId||i);return `<article><div class="v8-avatar">${esc((x.name||'角').slice(0,1))}</div><div><strong>${esc(x.name||'未命名角色')}</strong><small>${esc(x.activity||'独立生活')} · ${esc(x.mood||'平静')} · 精力 ${esc(x.energy??100)}</small></div><button data-route="npc" data-query="npc=${id}">档案</button></article>`}).join('')}</div>`)}
if(p==='map')return formPage('天下图','WORLD MAP','地点、势力与探索入口集中于此。地图保持沉浸式视觉，而不是后台表格。',`<div class="v8-map-canvas"><button class="v8-map-marker m1" data-route="runtime">主城</button><button class="v8-map-marker m2" data-route="runtime">旧城区</button><button class="v8-map-marker m3" data-route="runtime">远方</button><div class="v8-map-hint">选择地点进入场景 · 地图数据可由世界书继续扩展</div></div><div class="v8-inline-actions"><button data-route="runtime">进入剧情</button><button data-route="worldbook">编辑世界</button></div>`);
if(p==='api')return formPage('连接中心','CONNECTION CENTER','配置 AI 服务前先检查地址、权限与响应格式。密钥只保存在本地设置中，不在页面展示。',`<div class="v8-api-grid"><label>接口地址<input id="v8ApiUrl" placeholder="https://example.com/v1/chat/completions"></label><label>模型<input id="v8ApiModel" placeholder="模型名称"></label><label>鉴权方式<select id="v8ApiAuth"><option>Bearer Token</option><option>API Key Header</option></select></label><label>超时（秒）<input id="v8ApiTimeout" type="number" value="60"></label></div><div class="v8-diagnostic"><strong>连接诊断</strong><p id="v8Diag">尚未测试。点击“测试连接”后，这里会区分网络/CORS、401/403、404、429、5xx、超时及 JSON 格式错误。</p></div><div class="v8-editor-actions"><button id="v8ApiTest">测试连接</button><button id="v8ApiSave">保存设置</button><button data-v8="back">取消</button></div>`);
if(p==='assistant')return formPage('墨境助手','ASSISTANT WORKBENCH','助手按“读取 → 分析 → 方案 → 预览 → 确认 → 写入/导出”执行，不绕过 GitHub、浏览器或系统权限。',`<div class="v8-assistant-steps"><div class="active">01<br><b>读取</b></div><div>02<br><b>分析</b></div><div>03<br><b>方案</b></div><div>04<br><b>预览</b></div><div>05<br><b>确认</b></div><div>06<br><b>写入</b></div></div><div class="v8-assistant-grid"><textarea id="v8AssistantTask" placeholder="描述要修改的页面、功能或 Bug，例如：重做人物详情页，并检查移动端跳转。"></textarea><div class="v8-assistant-panel"><button id="v8AssistantRun">生成方案</button><button data-route="settings">权限与设置</button><pre id="v8AssistantResult">等待任务。助手会先分析，不会未经确认直接覆盖文件。</pre></div></div>`);
if(p==='memory')return formPage('长记忆','LONG MEMORY',`当前已索引 ${d.mem} 条记忆。支持长期检索，并可与世界书、预设分层注入。`,`<div class="v8-editor"><textarea id="v8Editor" placeholder="记录需要长期保留的世界事实、人物关系或剧情节点。">${esc((()=>{try{return localStorage.getItem('mo_long_memory_notes')||''}catch(e){return''}})())}</textarea><div class="v8-editor-actions"><button data-save-key="mo_long_memory_notes">保存</button><button data-v8="back">取消</button></div></div>`);
if(p==='prompts')return editor('提示词层级','mo_prompt_preset','小助手规则之后是预设、世界书、长期记忆；在此维护预设内容。');
if(p==='presets')return editor('预设中心','mo_presets','角色行为、文风、输出格式与世界运行规则。');
if(p==='worldbook')return editor('世界书','mo_worldbook','历史、地理、势力、规则、人物背景与世界事件。');
if(p==='regex')return editor('正则引擎','mo_regex_rules','每行一个规则：用于输出清洗、格式转换或内容后处理。');
if(p==='background')return formPage('背景库','SCENE ASSETS','上传背景、CG与场景素材；支持批量素材管理。',`<div class="v8-upload"><input id="v8BgFiles" type="file" accept="image/*" multiple><p>可一次选择多张图片。素材写入本地素材库后再由剧情调用。</p><button id="v8BgUpload">加入素材库</button></div>`);
if(p==='music')return formPage('音乐库','AUDIO LIBRARY','管理 BGM、MP3 与场景音频。',`<div class="v8-upload"><input id="v8MusicFiles" type="file" accept="audio/*,.mp3" multiple><p>支持 MP3 等浏览器可读取的音频格式。</p><button id="v8MusicUpload">加入音乐库</button></div>`);
if(p==='quest')return formPage('任务委托','QUESTS','任务随着世界事件推进，不只是静态清单。',`<div class="v8-list"><article><span>主线</span><h3>继续当前故事</h3><p>从当前场景继续推进。</p><button data-route="runtime">继续</button></article><article><span>探索</span><h3>前往未知地点</h3><p>打开地图寻找新的事件。</p><button data-route="map">探索</button></article></div>`);
if(p==='inventory')return formPage('背包','INVENTORY','物品、关键道具与任务物件。',`<div class="v8-empty"><b>背包等待世界产生物品</b><span>物品会在剧情、任务与事件中进入这里。</span><button data-route="runtime">回到剧情</button></div>`);
if(p==='relations')return formPage('关系网','RELATIONS','角色之间的关系会随着对话、事件和选择变化。',`<div class="v8-relation-map">${d.cast.slice(0,6).map((x,i)=>`<div class="v8-relation-node n${i+1}">${esc(x.name||'角色')}</div>`).join('')||'<div class="v8-empty">暂无角色关系数据</div>'}</div>`);
if(p==='settings')return formPage('系统设置','SETTINGS','统一管理连接、声音、界面与数据。',`<div class="v8-setting-grid"><button data-route="api"><strong>连接中心</strong><small>API / 模型 / 诊断</small></button><button data-route="assistant"><strong>墨境助手</strong><small>创作与代码工作台</small></button><button data-route="memory"><strong>长记忆</strong><small>检索与记忆管理</small></button><button data-route="background"><strong>素材库</strong><small>图片 / MP3 / CG</small></button></div>`);
return `<div class="v8-page"><div class="v8-page-top"><div><span class="v8-eyebrow">${esc((names[p]||'墨境').toUpperCase())}</span><h2>${esc(names[p]||'墨境世界')}</h2><p>该功能已接入统一高级文游页面层。</p></div><button class="v8-cancel" data-v8="back">取消 / 返回</button></div><div class="v8-card-grid"><button data-route="home"><strong>返回首页</strong><small>不丢失当前进度</small></button><button data-route="runtime"><strong>继续剧情</strong><small>回到沉浸式舞台</small></button><button data-route="assistant"><strong>墨境助手</strong><small>协助编辑与创作</small></button><button data-route="settings"><strong>设置</strong><small>连接与系统配置</small></button></div></div>`}
function mount(){if(document.getElementById('moV8Stage'))return;const el=document.createElement('div');el.id='moV8Stage';el.innerHTML='<div class="v8-head"><div><span class="v8-title">墨境</span><span class="v8-sub" id="moV8Sub"></span></div><div class="v8-actions"><button class="v8-btn" data-v8="back">返回</button><button class="v8-btn" data-v8="home">首页</button><button class="v8-btn" data-v8="more">更多</button></div></div><div class="v8-body" id="moV8Body"></div><div class="v8-foot" id="moV8Foot"></div></div>';document.body.appendChild(el);el.addEventListener('click',e=>{const r=e.target.closest('[data-route]');if(r){const qs=r.dataset.query||'';const obj={};qs.split('&').filter(Boolean).forEach(x=>{const a=x.split('=');obj[a[0]]=decodeURIComponent(a.slice(1).join('='))});go(r.dataset.route,Object.keys(obj).length?obj:null);return}const s=e.target.closest('[data-save-key]');if(s){try{localStorage.setItem(s.dataset.saveKey,document.getElementById('v8Editor')?.value||'');toast('已保存');}catch(err){toast('保存失败：'+reason(err))}return}const b=e.target.closest('[data-v8]');if(!b)return;const a=b.dataset.v8;if(a==='back')back();if(a==='home')go('home');if(a==='more')go('settings')});}
function bindPage(){document.getElementById('v8ApiTest')?.addEventListener('click',async()=>{const out=document.getElementById('v8Diag'),url=document.getElementById('v8ApiUrl')?.value?.trim();if(!url){out.textContent='失败：接口地址为空。请填写完整 HTTPS API 地址。';return}out.textContent='正在测试……';try{const ctl=new AbortController();const t=setTimeout(()=>ctl.abort(),Math.max(5,Number(document.getElementById('v8ApiTimeout')?.value||60))*1000);const res=await fetch(url,{method:'OPTIONS',signal:ctl.signal});clearTimeout(t);if(res.status===401||res.status===403)out.textContent=`失败：HTTP ${res.status}，服务器拒绝访问。检查 API Key、权限、Origin/CORS 配置。`;else if(res.status===404)out.textContent='失败：HTTP 404，接口路径不存在。检查 base URL 与 /chat/completions 等路径。';else if(res.status===405)out.textContent='服务器可达，但 HTTP 405 表示不允许 OPTIONS。请继续用真实模型请求测试，不能仅凭 OPTIONS 判断 API 是否可用。';else if(res.status===429)out.textContent='失败：HTTP 429，请求频率或额度受限。稍后重试并检查服务额度。';else if(res.status>=500)out.textContent=`失败：HTTP ${res.status}，上游服务异常。检查服务状态或稍后重试。`;else out.textContent=`连接可达：HTTP ${res.status}。注意：OPTIONS 成功不等于模型请求一定成功。`;}catch(e){out.textContent=e.name==='AbortError'?'失败：请求超时。检查网络、代理与服务响应时间。':`失败：${reason(e)}。若浏览器提示 Failed to fetch，优先检查 HTTPS、CORS、域名解析与接口是否可从当前浏览器直接访问。`}});
document.getElementById('v8ApiSave')?.addEventListener('click',()=>{try{localStorage.setItem('mo_api_url',document.getElementById('v8ApiUrl')?.value||'');localStorage.setItem('mo_api_model',document.getElementById('v8ApiModel')?.value||'');toast('连接设置已保存');}catch(e){toast('保存失败：'+reason(e))}});
document.getElementById('v8AssistantRun')?.addEventListener('click',async()=>{const task=document.getElementById('v8AssistantTask')?.value?.trim(),out=document.getElementById('v8AssistantResult');if(!task){out.textContent='请先描述任务。';return}out.textContent='正在分析任务与项目结构……';try{if(window.MOAssistant?.request){const r=await window.MOAssistant.request(task);out.textContent=typeof r==='string'?r:JSON.stringify(r,null,2)}else out.textContent='已生成执行框架：\n1. 读取相关页面与依赖\n2. 定位运行时入口\n3. 生成修改方案\n4. 预览变更\n5. 等待确认后写入。\n\n当前页面未检测到助手请求接口，因此不会假装已经修改文件。'}catch(e){out.textContent='助手执行失败：'+reason(e)+'\n排查：检查 API 连接、浏览器网络、助手权限。'}});
['v8BgUpload','v8MusicUpload'].forEach(id=>document.getElementById(id)?.addEventListener('click',()=>{const input=document.getElementById(id.replace('Upload','Files'));if(!input?.files?.length){toast('请先选择素材');return}try{if(window.MaterialLibrary?.addFiles){const r=window.MaterialLibrary.addFiles([...input.files]);if(r?.catch)r.catch(e=>toast('素材导入失败：'+reason(e)));toast(`已提交 ${input.files.length} 个素材`)}else toast('素材库模块未加载，请检查 material-library.js 是否成功加载。')}catch(e){toast('素材导入失败：'+reason(e))}}))}
function refresh(){mount();const p=route(),page=document.getElementById('page-'+p),shell=document.getElementById('moV8Stage');document.body.classList.add('mo-v8-app');document.querySelectorAll('.page-view').forEach(x=>x.classList.toggle('v8-immersive',x===page));const sub=document.getElementById('moV8Sub');if(sub)sub.textContent=names[p]||'墨境世界';const body=document.getElementById('moV8Body');if(body&&p!=='runtime')body.innerHTML=pageContent(p);shell.classList.toggle('v8-runtime-hidden',p==='runtime');const foot=document.getElementById('moV8Foot');if(foot)foot.innerHTML=nav.map(([id,label])=>'<button class="v8-nav '+(id===p?'active':'')+'" data-v8-route="'+id+'">'+esc(label)+'</button>').join('');foot?.querySelectorAll('[data-v8-route]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.v8Route)));bindPage()}
function boot(){refresh();window.addEventListener('hashchange',()=>setTimeout(refresh,0));document.addEventListener('keydown',e=>{if(e.key==='Escape')back()});new MutationObserver(()=>{if(!document.getElementById('moV8Stage'))mount()}).observe(document.body,{childList:true});window.MOPlatformV8={go,back,refresh}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();