/**
 * 墨境 Platform Upgrade v1
 * 目标：在不替换既有业务模块的前提下，补齐通用世界观、长记忆、正则、媒体、助手工作台等能力。
 */
(function(){
  'use strict';
  const LS={memory:'mo_long_memory_v1',api:'mo_assistant_api_v1'};
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const read=(k,d)=>{try{const v=localStorage.getItem(k);return v==null?d:JSON.parse(v)}catch(_){return d}};
  const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch(_){return false}};
  const ICONS={
    home:'M3 10.5 12 3l9 7.5M5 9v11h14V9M9 20v-6h6v6',map:'M3 6l6-3 6 3 6-3v15l-6 3-6-3-6 3V6M9 3v15M15 6v15',
    users:'M16 21v-2a4 4 0 0 0-4-4H7a4 4 0 0 0-4 4v2M9.5 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M17 8a3 3 0 0 1 0 6M21 21v-2a4 4 0 0 0-3-3.87',
    image:'M4 4h16v16H4zM8 9a1.5 1.5 0 1 0 0 .01M20 15l-5-5L5 20',music:'M9 18V5l12-2v13M6 21a3 3 0 1 0 0-6 3 3 0 0 0 0 6M18 19a3 3 0 1 0 0-6 3 3 0 0 0 0 6',
    memory:'M5 5h14v14H5zM8 9h8M8 12h6M8 15h5',assistant:'M4 5h16v12H4zM8 21h8M9 9h6M8 13h2M14 13h2',
    spark:'M12 2l1.8 6.2L20 10l-6.2 1.8L12 18l-1.8-6.2L4 10l6.2-1.8zM19 16l.8 2.2L22 19l-2.2.8L19 22l-.8-2.2L16 19l2.2-.8z',
    code:'M8 9l-4 3 4 3M16 9l4 3-4 3M14 5l-4 14',preview:'M3 5h18v14H3zM7 9l3 3-3 3M12 15h5',upload:'M12 16V4M7 9l5-5 5 5M4 20h16',download:'M12 4v12M7 11l5 5 5-5M4 20h16',
    settings:'M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.2 2.2-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1.02 1.56V20h-3.1v-.08a1.7 1.7 0 0 0-1.02-1.56 1.7 1.7 0 0 0-1.88.34l-.06.06-2.2-2.2.06-.06A1.7 1.7 0 0 0 4.6 15a1.7 1.7 0 0 0-1.56-1.02H3v-3.1h.08A1.7 1.7 0 0 0 4.64 9.9a1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.2-2.2.06.06A1.7 1.7 0 0 0 9.4 4.6V4h3.1v.08a1.7 1.7 0 0 0 1.02 1.56 1.7 1.7 0 0 0 1.88-.34l.06-.06 2.2 2.2-.06.06A1.7 1.7 0 0 0 17 9.4c.2.62.78 1.02 1.44 1.02H19v3.1h-.08A1.7 1.7 0 0 0 17.36 15',
    close:'M6 6l12 12M18 6L6 18',chat:'M4 5h16v11H7l-3 3z',shield:'M12 3l7 3v5c0 4.5-3 8-7 10-4-2-7-5.5-7-10V6z'
  };
  function icon(name){const d=ICONS[name]||ICONS.spark;return `<svg class="mo-svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="${d}"/></svg>`}
  function tokenize(text){return(String(text||'').toLowerCase().match(/[\u4e00-\u9fff]|[a-z0-9_]+/g)||[]).slice(0,1200)}
  function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
  function vector(text,n=192){const v=new Float32Array(n);for(const t of tokenize(text)){v[hash(t)%n]+=1;v[hash(':'+t)%n]+=.5}const norm=Math.hypot(...v)||1;for(let i=0;i<n;i++)v[i]/=norm;return Array.from(v)}
  function cosine(a,b){if(!a||!b)return 0;let s=0;for(let i=0;i<Math.min(a.length,b.length);i++)s+=a[i]*b[i];return s}
  function memory(){return read(LS.memory,[]).filter(x=>x&&x.text)}
  function saveMemory(item){const list=memory();item.id=item.id||('m_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7));item.createdAt=item.createdAt||Date.now();item.vector=item.vector||vector(item.text);item.importance=Math.max(0,Math.min(1,Number(item.importance??.5)));list.unshift(item);write(LS.memory,list.slice(0,3000));return item}
  function ingestMemory(text,meta={}){const s=String(text||'').trim();if(!s)return[];const out=[];for(let i=0;i<s.length;i+=700){const chunk=s.slice(i,i+900).trim();if(chunk)out.push(saveMemory({...meta,text:chunk,source:meta.source||'manual'}))}return out}
  function retrieveMemory(query,k=8){const q=vector(query),now=Date.now();return memory().map(m=>{const age=(now-(m.createdAt||now))/86400000;const recency=Math.exp(-age/30);const lexical=tokenize(query).filter(t=>String(m.text).toLowerCase().includes(t)).length;return {...m,score:cosine(q,m.vector)*.72+recency*.13+(m.importance||.5)*.1+Math.min(lexical,10)*.005}}).sort((a,b)=>b.score-a.score).slice(0,k)}
  window.LongMemory={get:memory,add:ingestMemory,search:retrieveMemory,clear:()=>write(LS.memory,[]),export:()=>JSON.stringify(memory(),null,2),import:j=>{const a=JSON.parse(j);if(Array.isArray(a))a.forEach(m=>m?.text&&saveMemory(m))}};
  function apiCfg(){return read(LS.api,{endpoint:'',key:'',model:'',imageEndpoint:''})}
  async function request(payload){const c=apiCfg();if(!c.endpoint)throw new Error('请先在助手里配置独立 API 地址');const h={'Content-Type':'application/json'};if(c.key)h.Authorization='Bearer '+c.key;const r=await fetch(c.endpoint,{method:'POST',headers:h,body:JSON.stringify({model:c.model,...payload})});if(!r.ok)throw new Error('API '+r.status);return r.json()}
  async function generateImage(prompt,size='1024x1024'){const c=apiCfg();if(!c.imageEndpoint)throw new Error('请先配置图像生成 API');const h={'Content-Type':'application/json'};if(c.key)h.Authorization='Bearer '+c.key;const r=await fetch(c.imageEndpoint,{method:'POST',headers:h,body:JSON.stringify({prompt,size,response_format:'url'})});if(!r.ok)throw new Error('图像 API '+r.status);const d=await r.json();return d?.data?.[0]?.url||d?.data?.[0]?.b64_json||d?.url||''}
  window.MOAssistant={request,generateImage,config:apiCfg,saveConfig:c=>write(LS.api,c)};
  window.MORegex={test:(p,f,t)=>{try{const r=new RegExp(p,f);return{ok:true,matches:[...String(t).matchAll(r)].slice(0,200).map(x=>({match:x[0],index:x.index,groups:x.slice(1)}))}}catch(e){return{ok:false,error:e.message}}},replace:(p,f,t,repl)=>{try{const r=new RegExp(p,f);return{text:String(t).replace(r,repl)}}catch(e){return{error:e.message}}}};
  window.MOVoice={speak:(text,o={})=>{if(!('speechSynthesis'in window))throw Error('当前浏览器不支持语音合成');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(String(text));u.lang=o.lang||'zh-CN';u.rate=o.rate||1;u.pitch=o.pitch||1;speechSynthesis.speak(u);return u},stop:()=>speechSynthesis?.cancel?.()};
  function toast(msg){try{App?.toast?.(msg,'success');return}catch(_){}const t=document.createElement('div');t.className='mo-up-toast';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2200)}
  function modal(title,body,wide=false){document.querySelector('.mo-up-modal')?.remove();const m=document.createElement('div');m.className='mo-up-modal';m.innerHTML=`<div class="mo-up-dialog ${wide?'wide':''}"><div class="mo-up-head"><b>${esc(title)}</b><button data-close>${icon('close')}</button></div><div class="mo-up-body">${body}</div></div>`;m.onclick=e=>{if(e.target===m||e.target.closest('[data-close]'))m.remove()};document.body.appendChild(m);return m}
  const FEATURES=[['memory','长记忆','分块 + 仿向量检索 + 重要度 + 时间衰减','memory'],['assistant','万能小助手','独立 API + 权限 + 文件工作区','assistant'],['image','生图工坊','任意时代、地域、世界观的视觉素材','image'],['music','声音工坊','MP3/音频 + 浏览器 TTS','voice'],['code','代码搜查','源文件导入后按文件名/内容搜索','code'],['preview','渲染预览','HTML 沙盒预览','preview'],['upload','素材批处理','图片/音频/视频批量导入','voice'],['shield','修改确认','分析 → 预览 → 用户确认 → 写入','assistant'],['users','NPC导演','群像角色引入与关系规则','npc'],['chat','群像编排','多角色同场、发言顺序、旁白','assistant'],['spark','剧情工具箱','分支、节奏、伏笔辅助','story'],['map','世界导航','地点、场景、世界线','map'],['download','存档中心','快照、导入、导出、回滚入口','backup'],['settings','工作区','主题、密度、字体、动画','settings'],['regex','正则工坊','测试、捕获组、替换预览','regex']];
  function hub(){const cards=FEATURES.map(f=>`<button class="mo-feature" data-feature="${f[3]}">${icon(f[0])}<b>${f[1]}</b><small>${f[2]}</small></button>`).join('');modal('墨境 · 创作与能力中枢',`<div class="mo-feature-grid">${cards}</div><div class="mo-up-note"><b>优先级：</b>小助手 ＞ 预设 ＞ 世界书 ＞ 长记忆。群像由预设定义，记忆负责补充事实，不覆盖高优先级设定。</div>`,'wide')}
  function memoryUI(){const rows=memory().slice(0,80).map(m=>`<article class="mo-memory-row"><b>${esc((m.text||'').slice(0,160))}</b><small>${esc(m.source||'manual')} · 重要度 ${Math.round((m.importance||0)*100)} · ${new Date(m.createdAt||Date.now()).toLocaleString()}</small></article>`).join('')||'<div class="mo-empty">还没有长记忆。</div>';modal('长记忆 · 仿向量检索',`<textarea id="moMemInput" placeholder="粘贴章节、对话、人物事实……"></textarea><div class="mo-row"><button class="mo-up-btn primary" id="moMemAdd">写入</button><button class="mo-up-btn" id="moMemSearch">检索</button><button class="mo-up-btn" id="moMemExport">导出</button><button class="mo-up-btn" id="moMemImport">导入</button></div><input id="moMemQuery" class="mo-up-input" placeholder="例如：某角色第一次见面发生了什么？"><div id="moMemResults" class="mo-memory-list">${rows}</div>`,'wide');const q=id=>document.getElementById(id);q('moMemAdd').onclick=()=>{const a=LongMemory.add(q('moMemInput').value,{importance:.6});toast(`已写入 ${a.length} 个片段`);q('moMemInput').value=''};q('moMemSearch').onclick=()=>{const r=LongMemory.search(q('moMemQuery').value,10);q('moMemResults').innerHTML=r.map(x=>`<article class="mo-memory-row"><b>${esc(x.text)}</b><small>相关度 ${(x.score*100).toFixed(1)}%</small></article>`).join('')||'<div class="mo-empty">没有找到相关记忆</div>'};q('moMemExport').onclick=()=>download('mojing-long-memory.json',LongMemory.export(),'application/json');q('moMemImport').onclick=()=>{const i=document.createElement('input');i.type='file';i.accept='.json';i.onchange=async()=>{try{LongMemory.import(await i.files[0].text());toast('记忆导入完成')}catch(e){toast('导入失败')}};i.click()}}
  function regexUI(){modal('正则工坊',`<input id="rxP" class="mo-up-input" placeholder="正则，例如：\\[\\[(.*?)\\]\\]"><input id="rxF" class="mo-up-input" value="g" placeholder="flags：gim"><textarea id="rxT" placeholder="待处理文本"></textarea><input id="rxR" class="mo-up-input" placeholder="替换文本，可用 $1、$2"><div class="mo-row"><button class="mo-up-btn primary" id="rxTest">测试</button><button class="mo-up-btn" id="rxRep">替换预览</button></div><pre id="rxOut" class="mo-code-out"></pre>`,'wide');rxTest.onclick=()=>{const r=MORegex.test(rxP.value,rxF.value,rxT.value);rxOut.textContent=r.ok?JSON.stringify(r.matches,null,2):r.error};rxRep.onclick=()=>{const r=MORegex.replace(rxP.value,rxF.value,rxT.value,rxR.value);rxOut.textContent=r.error||r.text}}
  function voiceUI(){modal('声音工坊',`<textarea id="voiceText" placeholder="旁白、角色台词……"></textarea><div class="mo-row"><select id="voiceLang" class="mo-up-input"><option value="zh-CN">中文</option><option value="en-US">English</option><option value="ja-JP">日本語</option><option value="ko-KR">한국어</option><option value="fr-FR">Français</option></select><button class="mo-up-btn primary" id="voiceGo">朗读</button><button class="mo-up-btn" id="voiceStop">停止</button><button class="mo-up-btn" id="mp3Pick">上传音频/MP3</button></div><div class="mo-up-note">上传后交给现有素材库；TTS 使用浏览器能力。</div>`);voiceGo.onclick=()=>MOVoice.speak(voiceText.value,{lang:voiceLang.value});voiceStop.onclick=MOVoice.stop;mp3Pick.onclick=()=>{const i=document.createElement('input');i.type='file';i.multiple=true;i.accept='audio/*';i.onchange=()=>MaterialLibrary?.importFiles?.(i.files);i.click()}}
  function imageUI(){modal('生图工坊',`<textarea id="imgPrompt" placeholder="场景、人物、镜头、光线、画风……支持现代、古代、西幻、科幻等世界观"></textarea><div class="mo-row"><select id="imgRatio" class="mo-up-input"><option>1024x1024</option><option>1536x1024</option><option>1024x1536</option></select><button class="mo-up-btn primary" id="imgGo">生成</button></div><div id="imgResult" class="mo-gen-result"></div>`,'wide');imgGo.onclick=async()=>{imgResult.textContent='生成中……';try{const u=await MOAssistant.generateImage(imgPrompt.value,imgRatio.value);imgResult.innerHTML=u?`<img src="${u.startsWith('data:')?u:esc(u)}" alt="生成结果">`:'接口未返回图片'}catch(e){imgResult.textContent=e.message}}}
  function sourceImport(){const i=document.createElement('input');i.type='file';i.multiple=true;i.accept='.js,.css,.html,.md,.json,.txt,.svg';i.onchange=async()=>{const arr=[];for(const f of i.files)arr.push({name:f.name,text:await f.text()});write('mo_source_workspace_v1',arr);toast(`已载入 ${arr.length} 个源文件`)};i.click()}
  function codeUI(){const fs=read('mo_source_workspace_v1',[]);modal('代码搜查',`<input id="codeQ" class="mo-up-input" placeholder="搜索文件名、函数、变量、错误信息……"><div id="codeR" class="mo-code-list">${fs.length?'已载入 '+fs.length+' 个文件':'请先导入源文件'}</div>`,'wide');codeQ.oninput=()=>{const q=codeQ.value.toLowerCase();codeR.innerHTML=fs.flatMap(f=>f.text.split(/\r?\n/).map((l,n)=>({f:f.name,n:n+1,l}))).filter(x=>!q||x.l.toLowerCase().includes(q)||x.f.toLowerCase().includes(q)).slice(0,300).map(x=>`<pre><b>${esc(x.f)}:${x.n}</b> ${esc(x.l)}</pre>`).join('')||'无匹配'}}
  function previewUI(){modal('渲染与预览',`<textarea id="pvCode" placeholder="粘贴 HTML。预览运行在 sandbox iframe 中。"></textarea><button class="mo-up-btn primary" id="pvGo">渲染</button><iframe id="pvFrame" class="mo-preview-frame" sandbox="allow-scripts"></iframe>`,'wide');pvGo.onclick=()=>pvFrame.srcdoc=pvCode.value}
  function assistantUI(){const c=apiCfg();modal('万能小助手 · 独立工作台',`<div class="mo-up-note"><b>权限链：</b>读取 → 分析 → 生成方案 → 预览 → 用户确认 → 写入。默认不覆盖文件。</div><label>API Endpoint<input id="asEp" class="mo-up-input" value="${esc(c.endpoint)}"></label><label>Model<input id="asModel" class="mo-up-input" value="${esc(c.model)}"></label><label>API Key（仅本机存储）<input id="asKey" type="password" class="mo-up-input" value="${esc(c.key)}"></label><label>图像 API Endpoint<input id="asImg" class="mo-up-input" value="${esc(c.imageEndpoint)}"></label><div class="mo-row"><button class="mo-up-btn primary" id="asSave">保存</button><button class="mo-up-btn" id="asFile">导入源文件</button><button class="mo-up-btn" id="asCode">代码搜查</button><button class="mo-up-btn" id="asPreview">渲染预览</button></div><div class="mo-up-note">可接 OpenAI 风格 JSON 接口。生产环境建议用自己的后端代理，不把长期密钥公开给浏览器。</div>`,'wide');asSave.onclick=()=>{MOAssistant.saveConfig({endpoint:asEp.value.trim(),model:asModel.value.trim(),key:asKey.value,imageEndpoint:asImg.value.trim()});toast('助手 API 已保存')};asFile.onclick=sourceImport;asCode.onclick=codeUI;asPreview.onclick=previewUI}
  function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  function mount(){if(document.getElementById('moUpgradeFab'))return;const fab=document.createElement('button');fab.id='moUpgradeFab';fab.innerHTML=icon('spark')+'<span>能力</span>';fab.onclick=hub;document.body.appendChild(fab);document.addEventListener('click',e=>{const f=e.target.closest('[data-feature]');if(!f)return;document.querySelector('.mo-up-modal')?.remove();({memory:memoryUI,assistant:assistantUI,image:imageUI,voice:voiceUI,regex:regexUI,code:codeUI,preview:previewUI,media:voiceUI,npc:()=>App?.navigate?.('npc'),story:()=>App?.navigate?.('storyline'),map:()=>App?.navigate?.('map'),backup:()=>App?.navigate?.('backup'),settings:()=>App?.navigate?.('settings')})[f.dataset.feature]?.()});document.addEventListener('dblclick',e=>{const t=e.target.closest('.message,.dialogue,.chat-message,.story-text,.mo-dialogue');if(t?.textContent?.trim())MOVoice.speak(t.textContent.trim())})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
