/* 墨境 v9：页面级文游信息层。只负责编排，不破坏既有业务 DOM。 */
(function(){'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const route=()=>location.hash.replace(/^#/,'')||'home';
const go=p=>{try{if(window.App?.navigate){App.navigate(p);return}if(window.App?.go){App.go(p);return}}catch(e){window.App?.toast?.('跳转失败：'+(e.message||e),'error',3500)}location.hash='#'+p};
const back=()=>{try{if(window.App?.back){App.back();return}}catch(e){} history.back()};
function profiles(){try{return window.MOWorldV2?.getProfiles?.()||window.MOWorldV2?.getGroupCast?.(12)||[]}catch(e){return[]}}
function memoryCount(){try{return window.LongMemory?.search?.('',10000)?.length||0}catch(e){return 0}}
function worldName(){try{return localStorage.getItem('currentWorldName')||localStorage.getItem('worldName')||'未命名世界'}catch(e){return'未命名世界'}}
function shell(title,eyebrow,body){return `<div class="v9-page"><div class="v9-page-head"><button data-v9="back">‹ 返回</button><div><span>${esc(eyebrow)}</span><h2>${esc(title)}</h2></div><button data-v9="home">首页</button></div>${body}</div>`}
function render(p){let body='';const ps=profiles();
 if(p==='worldview'||p==='world-selector') body=`<section class="v9-cover"><div><span>WORLD DOSSIER</span><h1>${esc(worldName())}</h1><p>把世界观、势力、人物与规则组织成一个可以持续运行的舞台。</p></div><div class="v9-actions"><button data-v9-route="map">进入天下图</button><button data-v9-route="worldbook">编辑世界书</button><button data-v9-route="npc">人物志</button></div></section><div class="v9-info-grid"><article><b>角色</b><strong>${ps.length}</strong><small>已载入独立生活档案</small></article><article><b>长期记忆</b><strong>${memoryCount()}</strong><small>可参与剧情检索</small></article><article><b>剧情</b><strong>沉浸式</strong><small>自由输入行动</small></article></div>`;
 else if(p==='npc'){body=`<div class="v9-cast-grid">${(ps.length?ps:[{name:'暂无角色',mood:'—',activity:'请在人物志中创建角色'}]).map(x=>`<article class="v9-cast-card"><div class="v9-portrait">${esc((x.name||'人').slice(0,1))}</div><div class="v9-cast-main"><span>CAST</span><h3>${esc(x.name||'未命名')}</h3><p>${esc(x.activity||'独立生活')}</p><small>心情 · ${esc(x.mood||'平静')}　精力 · ${esc(x.energy??'—')}</small></div><button data-v9-route="runtime">进入剧情</button></article>`).join('')}</div>`}
 else if(p==='relations') body=`<div class="v9-empty"><span>RELATION GRAPH</span><h3>关系网</h3><p>关系数据将随角色互动、事件和长期记忆持续变化。</p><div class="v9-actions"><button data-v9-route="npc">查看人物志</button><button data-v9-route="runtime">回到剧情</button></div></div>`;
 else if(p==='quest') body=`<div class="v9-list"><article><b>当前主线</b><h3>让世界开始运转</h3><p>进入剧情，与世界中的角色建立第一条事件链。</p><button data-v9-route="runtime">继续</button></article><article><b>探索</b><h3>发现一个地点</h3><p>从天下图选择地点，并观察世界状态。</p><button data-v9-route="map">前往地图</button></article></div>`;
 else if(p==='inventory') body=`<div class="v9-empty"><span>INVENTORY</span><h3>随身物品</h3><p>物品会在剧情事件、任务与角色行为中产生变化。</p><button data-v9-route="runtime">回到剧情</button></div>`;
 else if(p==='api') body=`<div class="v9-connection"><div><span>CONNECTION CENTER</span><h3>AI 连接中心</h3><p>这里集中处理接口、鉴权、网络与服务端返回错误。</p></div><div class="v9-error-grid"><article><b>401 / 403</b><small>检查 API Key、权限或模型访问资格。</small></article><article><b>404</b><small>检查 Endpoint、模型名称和路径。</small></article><article><b>429</b><small>检查额度、限流与请求频率。</small></article><article><b>5xx / 网络</b><small>检查服务状态、网络、CORS 与代理。</small></article></div><button data-v9-route="settings">打开设置</button></div>`;
 else body=`<div class="v9-empty"><span>MODULE</span><h3>${esc(p)}</h3><p>该模块保留原业务入口，页面正在统一到高级文游信息层。</p><div class="v9-actions"><button data-v9-route="runtime">继续剧情</button><button data-v9-route="home">回到首页</button></div></div>`;
 const page=$('#page-'+p);if(!page||p==='runtime')return;page.classList.add('v9-page-host');page.innerHTML=shell(({worldview:'世界档案','world-selector':'选择世界',npc:'人物志',relations:'关系网',quest:'任务委托',inventory:'背包',api:'连接中心'}[p]||'墨境'),({worldview:'WORLD', 'world-selector':'WORLDS',npc:'CAST',relations:'RELATIONS',quest:'QUEST',inventory:'INVENTORY',api:'API'}[p]||'MOJING'),body);page.querySelectorAll('[data-v9-route]').forEach(b=>b.onclick=()=>go(b.dataset.v9Route));page.querySelector('[data-v9="back"]')?.addEventListener('click',back);page.querySelector('[data-v9="home"]')?.addEventListener('click',()=>go('home'))}
function boot(){const f=()=>render(route());f();window.addEventListener('hashchange',()=>setTimeout(f,0));window.MOPlatformV9={render,go,back};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();