/* 墨境平台 v6：统一路由、页面壳、返回/取消、SVG、移动端导航。只给页面加平台层，不搬动业务 DOM。 */
(function(){'use strict';
const names={home:'首页',runtime:'剧情',map:'地图',npc:'人物志',background:'背景库',music:'音乐',inventory:'背包',quest:'任务',relations:'关系',memory:'长记忆',worldbook:'世界书',prompts:'提示词',presets:'预设',regex:'正则工坊',assistant:'墨境小助手',api:'AI API',chat:'聊天',plugins:'插件',notes:'记事册',timeline:'时间线',events:'世界事件',storyline:'故事线',settings:'设置','settings-hub':'设置','world-selector':'选择世界','world-detail':'世界详情','cg-gallery':'CG画廊','material-library':'素材库','ui-diy':'界面工坊','code-patcher':'代码工坊','custom-creator':'功能创建','design-suite':'设计套件','system-builder':'系统生成器',backup:'备份',worldview:'世界观',achievement:'成就',weather:'天气时辰',chapter-editor:'章节编辑',text-novel:'文字小说',scene:'场景'};
const paths={home:'M3 10.5 12 3l9 7.5v10h-6v-6H9v6H3z',map:'M3 6l6-3 6 3 6-3v15l-6 3-6-3-6 3zM9 3v15M15 6v15',users:'M16 21v-2a4 4 0 0 0-4-4H7a4 4 0 0 0-4 4v2M9.5 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M17 8a3 3 0 1 1 0 6M21 21v-2a4 4 0 0 0-3-3.8',bag:'M5 8h14v12H5zM8 8V6a4 4 0 0 1 8 0v2',quest:'M5 4h14v16H5zM8 8h8M8 12h6M8 16h5',relations:'M6 6a3 3 0 1 0 0 6 3 3 0 0 0 0-6zm12 0a3 3 0 1 0 0 6 3 3 0 0 0 0-6zM9 9h6M8 20a4 4 0 0 1 8 0',settings:'M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7M19 13v-2l-2-.5a6 6 0 0 0-.7-1.7l1.1-1.8-1.4-1.4-1.8 1.1a6 6 0 0 0-1.7-.7L12 4h-2l-.5 2a6 6 0 0 0-1.7.7L6 5.6 4.6 7l1.1 1.8A6 6 0 0 0 5 10.5L3 11v2l2 .5a6 6 0 0 0 .7 1.7L4.6 17 6 18.4l1.8-1.1a6 6 0 0 0 1.7.7l.5 2h2l.5-2a6 6 0 0 0 1.7-.7l1.8 1.1 1.4-1.4-1.1-1.8a6 6 0 0 0 .7-1.7z',chat:'M4 5h16v11H7l-3 3z',spark:'M12 2l1.8 6.2L20 10l-6.2 1.8L12 18l-1.8-6.2L4 10l6.2-1.8z',more:'M5 12h.01M12 12h.01M19 12h.01',back:'M15 5l-7 7 7 7'};
const icon=k=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="${paths[k]||paths.spark}"/></svg>`;
const nav=[['home','首页'],['map','地图'],['npc','人物'],['quest','任务'],['relations','关系'],['inventory','背包']];
function route(){return(location.hash||'#home').slice(1).split('?')[0]||'home'}
function go(id){if(window.App&&typeof App.navigate==='function')App.navigate(id);else location.hash=id}
function back(){const r=route();if(r==='home')return;const prev=sessionStorage.getItem('mo_v6_prev');go(prev&&prev!==r?prev:'home')}
function shell(){if(document.getElementById('moV6Shell'))return;const e=document.createElement('div');e.id='moV6Shell';e.innerHTML=`<header class="v6-top"><button class="v6-brand" onclick="App.navigate('home')"><span class="v6-logo">墨</span><span><b>墨境</b><small>AI VISUAL NOVEL PLATFORM</small></span></button><div class="v6-status"><span class="v6-pill" id="v6loc">⌖ 无界</span><span class="v6-pill" id="v6date">◷ 未定</span></div><div class="v6-top-actions"><button class="v6-btn optional" onclick="App.navigate('assistant')">小助手</button><button class="v6-btn optional" onclick="App.navigate('settings')">设置</button><button class="v6-btn" aria-label="返回" onclick="window.MOPlatformV6.back()">${icon('back')}</button></div></header><nav class="v6-bottom">${nav.map(([id,t])=>`<button class="v6-nav" data-route="${id}" onclick="App.navigate('${id}')">${icon(id==='npc'?'users':id)}<span>${t}</span></button>`).join('')}<button class="v6-nav" onclick="window.MOPlatformV6.more()">${icon('more')}<span>更多</span></button></nav><div class="v6-more" id="v6more"><div class="v6-more-grid">${Object.keys(names).filter(k=>!nav.some(n=>n[0]===k)&&k!=='home').slice(0,24).map(k=>`<button onclick="App.navigate('${k}');window.MOPlatformV6.more(false)">${icon(k==='assistant'?'spark':k==='chat'?'chat':k==='settings'?'settings':'spark')}<br>${names[k]}</button>`).join('')}</div></div>`;document.body.appendChild(e)}
function mark(page){if(!page)return;const id=page.id.replace('page-','');if(!names[id])return;page.classList.add('v6-page');page.dataset.v6='1'}
function scan(){shell();document.querySelectorAll('.page-view').forEach(mark);const r=route();document.querySelectorAll('.v6-nav').forEach(x=>x.classList.toggle('active',x.dataset.route===r));const loc=document.getElementById('v6loc'),date=document.getElementById('v6date');try{if(loc)loc.textContent='⌖ '+(window.Storage?.get?.('currentLocation','无界')||'无界');if(date)date.textContent='◷ '+(window.Storage?.get?.('currentDate','未定')||'未定')}catch(_){} }
function bind(){window.MOPlatformV6={back,more:v=>{const x=document.getElementById('v6more');if(x)x.classList.toggle('show',v===undefined?!x.classList.contains('show'):!!v)},scan};scan();new MutationObserver(()=>scan()).observe(document.body,{childList:true,subtree:true});window.addEventListener('hashchange',()=>{const now=route(),old=sessionStorage.getItem('mo_v6_route');if(old&&old!==now)sessionStorage.setItem('mo_v6_prev',old);sessionStorage.setItem('mo_v6_route',now);setTimeout(scan,30)});document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.getElementById('v6more')?.classList.remove('show');document.querySelectorAll('.mo-overlay,.mo-modal,[role="dialog"]').forEach(x=>{if(x.classList.contains('is-open'))x.classList.remove('is-open')})}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
