/* 墨境 VN UI v3：统一视觉小说舞台、Markdown/VN切换、自由输入、群像入口、素材入口。 */
(function(){'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=(m)=>{let x=document.querySelector('.mo-v3-toast');if(!x){x=document.createElement('div');x.className='mo-v3-toast';document.body.appendChild(x)}x.textContent=m;clearTimeout(x._t);x._t=setTimeout(()=>x.remove(),2800)};
const icons={home:'<svg viewBox="0 0 24 24"><path d="m3 11 9-8 9 8"/><path d="M5 10v10h14V10M9 20v-6h6v6"/></svg>',map:'<svg viewBox="0 0 24 24"><path d="M4 5l6-2 4 2 6-2v16l-6 2-4-2-6 2z"/><path d="M10 3v16M14 5v16"/></svg>',people:'<svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><circle cx="17" cy="9" r="2.5"/><path d="M3 20c.4-4 2.5-6 6-6s5.6 2 6 6M14 15c3.7-.7 6.2 1 7 5"/></svg>',bag:'<svg viewBox="0 0 24 24"><path d="M5 8h14l1 13H4z"/><path d="M9 8a3 3 0 0 1 6 0"/></svg>',task:'<svg viewBox="0 0 24 24"><path d="M6 3h12v18H6z"/><path d="m9 8 1.5 1.5L14 6M9 13h6M9 17h4"/></svg>',more:'<svg viewBox="0 0 24 24"><circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/></svg>'};
function nav(route){try{window.App?.navigate?.(route)}catch(e){toast('页面跳转失败：'+e.message)}}
function open(){if(document.getElementById('moV3Stage'))return;const host=document.body,s=document.createElement('div');s.id='moV3Stage';s.className='mo-v3-stage';s.innerHTML=`<div class="mo-v3-bg"></div><div class="mo-v3-vignette"></div><header class="mo-v3-top"><button class="mo-v3-icon" id="v3Back">←</button><b class="mo-v3-title">墨境 · 当前世界</b><span class="mo-v3-meta" id="v3Meta">春 · 第三日 · 晚间</span><span class="spacer"></span><button class="mo-v3-icon" id="v3Sound">♫</button><button class="mo-v3-icon" id="v3Menu">☰</button></header><aside class="mo-v3-side"><button id="v3Cast">群</button><button id="v3Assets">图</button></aside><div class="mo-v3-dialogue"><div class="mo-v3-name" id="v3Name">旁白</div><div class="mo-v3-text" id="v3Text">世界正在继续运转。即使你没有看见，角色也有自己的生活。</div><div class="mo-v3-input"><textarea id="v3Input" placeholder="自由输入你的行动、台词或问题……"></textarea><button class="mo-v3-btn primary" id="v3Send">发送</button></div></div><div class="mo-v3-mode"><button data-mode="vn" class="active">沉浸式</button><button data-mode="md">Markdown</button></div><nav class="mo-v3-bottom">${[['home','首页'],['map','地图'],['people','人物'],['bag','背包'],['task','任务'],['more','更多']].map(([k,t])=>`<button class="mo-v3-nav" data-route="${k}">${icons[k]}${t}</button>`).join('')}</nav><div class="mo-v3-markdown" id="v3Markdown"><div class="mo-v3-markdown-inner"><h1>当前剧情</h1><article id="v3MdText"></article></div></div>`;host.appendChild(s);s.querySelector('#v3Back').onclick=()=>s.remove();s.querySelector('#v3Send').onclick=send;s.querySelector('#v3Input').addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();send()}});s.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>mode(b.dataset.mode));s.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{s.remove();nav(b.dataset.route)});s.querySelector('#v3Cast').onclick=()=>window.WorldSimulation?.openGroup?.()||toast('群像导演模块尚未加载');s.querySelector('#v3Assets').onclick=()=>nav('material-library');s.querySelector('#v3Menu').onclick=()=>toast('更多功能：设置、记忆、世界书、助手与存档');s.querySelector('#v3Sound').onclick=()=>nav('music')}
function mode(m){const s=document.getElementById('moV3Stage');if(!s)return;s.querySelector('[data-mode="vn"]').classList.toggle('active',m==='vn');s.querySelector('[data-mode="md"]').classList.toggle('active',m==='md');s.querySelector('.mo-v3-dialogue').style.display=m==='vn'?'block':'none';s.querySelector('#v3Markdown').style.display=m==='md'?'block':'none';s.querySelector('#v3MdText').innerHTML=esc(s.querySelector('#v3Text').textContent).replace(/\n/g,'<br>');window.VNEngineV2?.patch?.({mode:m})}
async function send(){const s=document.getElementById('moV3Stage'),input=s?.querySelector('#v3Input');if(!input)return;const text=input.value.trim();if(!text)return;input.value='';s.querySelector('#v3Name').textContent='你';s.querySelector('#v3Text').textContent=text;try{toast('世界正在回应……');let r=window.VNEngineV2?.send?await window.VNEngineV2.send(text):window.NovelRuntime?.genAIReply?await window.NovelRuntime.genAIReply(text):null;if(r==null)throw Error('AI运行时未加载，请检查 API/聊天模块');const out=typeof r==='string'?r:(r.text||r.content||'世界暂时没有回应。');window.VNEngineV2?.renderResult?.(out);if(!window.VNEngineV2) s.querySelector('#v3Text').textContent=out}catch(e){toast('发送失败：'+(e.message||'未知原因'))}}
window.MoV3={open,mode,send};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(open,700));else setTimeout(open,700);
})();
