/* 墨境 VN UI v5：高级文游舞台。默认不强制覆盖所有页面；由首页/运行页显式进入。 */
(function(){'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=m=>{let x=document.querySelector('.mo-v3-toast');if(!x){x=document.createElement('div');x.className='mo-v3-toast';document.body.appendChild(x)}x.textContent=m;clearTimeout(x._t);x._t=setTimeout(()=>x.remove(),2800)};
const routes={home:'home',map:'map',people:'npc',bag:'inventory',task:'quest',more:'settings-hub'};
const icons={home:'⌂',map:'◇',people:'♙',bag:'▱',task:'☷',more:'⋯'};
function nav(r){try{window.App?.navigate?.(routes[r]||r)}catch(e){toast('页面跳转失败：'+e.message)}}
function worldMeta(){try{const t=window.TimelineSystem?.getState?.()||window.TimelineSystem?.state||{};return [t.season||'春',t.day?`第${t.day}日`:'',t.shichen||t.period||'夜'].filter(Boolean).join(' · ')}catch(e){return '当前世界 · 旅途进行中'}}
function open(opts={}){if(document.getElementById('moV3Stage'))return;const s=document.createElement('div');s.id='moV3Stage';s.className='mo-v3-stage mo-v5-stage';s.innerHTML=`<div class="mo-v3-bg"></div><div class="mo-v3-vignette"></div><header class="mo-v3-top"><button class="mo-v3-icon" id="v3Back" aria-label="返回">‹</button><b class="mo-v3-title">墨境 · ${esc(opts.title||'当前世界')}</b><span class="mo-v3-meta" id="v3Meta">${esc(worldMeta())}</span><span class="spacer"></span><button class="mo-v3-icon" id="v3Sound">♫</button><button class="mo-v3-icon" id="v3Menu">☰</button></header><aside class="mo-v3-side"><button id="v3Cast">群像</button><button id="v3Assets">素材</button></aside><div class="mo-v3-dialogue"><div class="mo-v3-name" id="v3Name">旁白</div><div class="mo-v3-text" id="v3Text">世界正在继续运转。角色拥有自己的目标、关系与生活。</div><div class="mo-v3-input"><textarea id="v3Input" placeholder="输入你的行动、台词或想法……"></textarea><button class="mo-v3-btn primary" id="v3Send">继续</button></div></div><div class="mo-v3-mode"><button data-mode="vn" class="active">沉浸剧情</button><button data-mode="md">文本</button></div><nav class="mo-v3-bottom">${[['home','首页'],['map','地图'],['people','人物'],['bag','背包'],['task','任务'],['more','更多']].map(([k,t])=>`<button class="mo-v3-nav" data-route="${k}"><span style="font-size:18px">${icons[k]}</span>${t}</button>`).join('')}</nav><div class="mo-v3-markdown" id="v3Markdown"><div class="mo-v3-markdown-inner"><h1>当前剧情</h1><article id="v3MdText"></article></div></div>`;document.body.appendChild(s);
 s.querySelector('#v3Back').onclick=()=>s.remove();s.querySelector('#v3Send').onclick=send;s.querySelector('#v3Input').addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();send()}});s.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>mode(b.dataset.mode));s.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{s.remove();nav(b.dataset.route)});s.querySelector('#v3Cast').onclick=()=>window.WorldSimulation?.openGroup?.()||window.MOWorldV2?.openGroup?.()||toast('群像模块尚未加载');s.querySelector('#v3Assets').onclick=()=>{s.remove();nav('material-library')};s.querySelector('#v3Menu').onclick=()=>{s.remove();nav('settings-hub')};s.querySelector('#v3Sound').onclick=()=>{s.remove();nav('music')};return s}
function mode(m){const s=document.getElementById('moV3Stage');if(!s)return;s.querySelector('[data-mode="vn"]').classList.toggle('active',m==='vn');s.querySelector('[data-mode="md"]').classList.toggle('active',m==='md');s.querySelector('.mo-v3-dialogue').style.display=m==='vn'?'block':'none';s.querySelector('#v3Markdown').style.display=m==='md'?'block':'none';s.querySelector('#v3MdText').innerHTML=esc(s.querySelector('#v3Text').textContent).replace(/\n/g,'<br>');window.VNEngineV2?.patch?.({mode:m})}
async function send(){const s=document.getElementById('moV3Stage'),input=s?.querySelector('#v3Input');if(!input)return;const text=input.value.trim();if(!text)return;input.value='';s.querySelector('#v3Name').textContent='你';s.querySelector('#v3Text').textContent=text;try{toast('世界正在回应……');let r=window.VNEngineV2?.send?await window.VNEngineV2.send(text):window.NovelRuntime?.genAIReply?await window.NovelRuntime.genAIReply(text):null;if(r==null)throw Error('AI运行时未加载，请检查 API、网络或聊天模块');const out=typeof r==='string'?r:(r.text||r.content||'世界暂时没有回应。');window.VNEngineV2?.renderResult?.(out);if(!window.VNEngineV2)s.querySelector('#v3Text').textContent=out}catch(e){toast('发送失败：'+(e.message||'未知原因'))}}
window.MoV3={open,mode,send,nav};
})();
